version: "3.9"
services:
  db:
    image: postgres
    container_name: postgressql_cartera
    ports:
      - "5431:5432"
    networks:
      - mi_red
    environment:
      - POSTGRES_DB=dockerizandoDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - C:\\postgres_datapart:/var/lib/postgresql/data
    restart: always

#  eureka:
#    build: ./microservicios-eureka
#    container_name: testapp_eureka
#    ports:
 #     - "8761:8761"
 #   networks:
#      - mi_red
#    environment:
#      - eureka.client.register-with-eureka=false
 #     - eureka.client.fetch-registry=false
#    restart: always

#  backend:
 #   build: ./microservicio-usurios
  #  container_name: testapp_usuario
  #  ports:
   #   - "8085:8085"
 #   networks:
  #    - mi_red
  #  environment:
   #   - DATABASE_URL=jdbc:postgresql://db:5432/dockerizandoDB
   #   - DATABASE_USERNAME=postgres
   #   - DATABASE_PASSWORD=root
   #   - eureka.client.service-url.defaultZone=http://eureka:8761/eureka/
  #  depends_on:
  #    - db
  #    - eureka
 #   restart: always

 # cartera:
  #  build: ./microservicio-cartera
 #   container_name: testapp_cartera
 #   ports:
#      - "8087:8087"
  #  networks:
 #     - mi_red
  #  environment:
  #    - DATABASE_URL=jdbc:postgresql://db:5432/dockerizandoDB
 #     - DATABASE_USERNAME=postgres
 #     - DATABASE_PASSWORD=root
 #     - EUREKA_ZONE=http://eureka:8761/eureka/
 #   depends_on:
 #     - db
 #     - eureka
 #   restart: always
#  zuul:
#    build: ./microservicio-zuul
#    container_name: testapp_zuul
 #   ports:
#      - "8090:8090"
#    networks:
#      - mi_red
 #   environment:
 #     - eureka.client.service-url.defaultZone=http://eureka:8761/eureka/
 #   depends_on:
  #    - eureka
 #   restart: always

networks:
  mi_red:
    external:
      name: mi_red


